# Generated by Django 4.1.3 on 2022-11-06 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='datetime_modified',
            new_name='date_time_modified',
        ),
    ]
