# Generated by Django 4.1.3 on 2022-11-10 10:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Blog', '0003_blog_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(verbose_name='body')),
                ('stars', models.CharField(choices=[('1', 'very bad'), ('2', 'bad'), ('3', 'good'), ('4', 'very good')], max_length=10, verbose_name='stars')),
                ('datetime_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='datetime_created')),
                ('datetime_modified', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='Blog.blog')),
            ],
        ),
    ]
